### ISSUE TITLE
Installation fails due to `influxdb/client/v2`

### ISSUE THREAD

**Issue by beniz** [jolibrain/livedetect#1]
Error is below:

```
 go get -u github.com/jolibrain/livedetect
package github.com/influxdata/influxdb/client/v2: cannot find package "github.com/influxdata/influxdb/client/v2" in any of:
        /usr/local/go/src/github.com/influxdata/influxdb/client/v2 (from $GOROOT)
        /home/pi/go/src/github.com/influxdata/influxdb/client/v2 (from $GOPATH)
```

**Comment by CorentinB** [comment]
It looks like InfluxDB changed a lot of things regarding their way to distribute their clients.
The new repo for the v2 client is https://github.com/influxdata/influxdb1-client as I can understand.

The old `github.com/influxdata/influxdb/client/v2` URL now point to a 404 error page.

EDIT: you can maybe find more informations about their new distribution model on their current repository: https://github.com/influxdata/influxdb

**Comment by beniz** [comment]
Thanks, fixed.
