### ISSUE TITLE
Installation fails due to `influxdb/client/v2` 

### ISSUE THREAD

**Issue by florentinolim** [jolibrain/livedetect#2]
I have this error while installing influxdb

[root@mq gowork]#  go get -u github.com/influxdata/influxdb/client/v2
package github.com/influxdata/influxdb/client/v2: cannot find package "github.com/influxdata/influxdb/client/v2" in any of:
        /usr/lib/golang/src/github.com/influxdata/influxdb/client/v2 (from $GOROOT)
        /opt/gowork/src/github.com/influxdata/influxdb/client/v2 (from $GOPATH)
[root@mq gowork]#

**Comment by beniz** [comment]
Hi, I've seen this before, this is due to a change with influxdb client. I believe we have a fix. In the meantime, if you are not using influxdb, you can comment it out in the code. Livedetect has not been officially released but it will soon, thanks for reporting this.

**Comment by beniz** [comment]
See #1 as this looks similar though fixed

**Comment by beniz** [comment]
So this should not happen. Try to `git pull` to make sure you are using the last version of livedetect.
